PREFIX schema: <http://schema.org/>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX lblodBesluit: <http://lblod.data.gift/vocabularies/besluit/>
PREFIX rule: <http://lblod.data.gift/vocabularies/notification/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?besluitDocumentType ?label ?rule ?validFrom ?validThrough
WHERE {
  ?besluitDocumentType a skos:Concept;
    lblodBesluit:notificationRule ?rule;
    skos:prefLabel ?label.

  ?rule a rule:NotificationRule;
        lblodBesluit:decidableBy <http://data.vlaanderen.be/id/concept/BestuurseenheidClassificatieCode/5ab0e9b8a3b2ca7c5e000001>;
        lblodBesluit:obligationToReport "true"^^xsd:boolean.

  OPTIONAL { ?rule schema:validFrom ?validFrom . }
  OPTIONAL { ?rule schema:validThrough ?validThrough . }
}