PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX meb:  <http://rdf.myexperiment.org/ontologies/base/>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX adms: <http://www.w3.org/ns/adms#>

SELECT DISTINCT ?submission ?status ?statusLabel WHERE {
  ?submission
    a meb:Submission ;
    dct:subject
      <http://gemeente.be/uri/van/het/ingezonden/besluit/ceecdbb0-699b-11ed-b29d-cb0aa48f5e37> ;
    adms:status ?status .

  ?status skos:prefLabel ?statusLabel.
}
