PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?bestuurseenheidUri ?bestuureenheidLabel ?classificatieLabel
WHERE {
  ?bestuurseenheidUri
    a besluit:Bestuurseenheid ;
    skos:prefLabel ?bestuurseenheidNaam ;
    besluit:classificatie ?classificatieUri ;
    skos:prefLabel ?bestuureenheidLabel ;
    besluit:werkingsgebied ?werkinsgebiedUri .

  ?classificatieUri skos:prefLabel ?classificatieLabel .
}
