PREFIX fo:      <http://www.w3.org/1999/XSL/Format#>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX org:     <http://www.w3.org/ns/org#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX besluit: <http://data.vlaanderen.be/ns/besluit#>
PREFIX mandaat: <http://data.vlaanderen.be/ns/mandaat#>
PREFIX persoon: <http://data.vlaanderen.be/ns/persoon#>

SELECT DISTINCT ?persoonUri ?roleLabel ?naam ?achternaam
WHERE {
  ?bestuursorgaanInPeriodeUri
    a besluit:Bestuursorgaan ;
    org:hasPost ?mandaatUri .

  ?mandaatUri org:role ?roleUri .
  ?roleUri skos:prefLabel ?roleLabel .

  ?mandatarisUri org:holds ?mandaatUri ;
    mandaat:isBestuurlijkeAliasVan ?persoonUri .

  ?persoonUri persoon:gebruikteVoornaam ?naam ;
    foaf:familyName ?achternaam .
}
