PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX meb: <http://rdf.myexperiment.org/ontologies/base/>
PREFIX nmo: <http://www.semanticdesktop.org/ontologies/2007/03/22/nmo#>
PREFIX pav: <http://purl.org/pav/>
PREFIX ere: <http://data.lblod.info/vocabularies/erediensten/>

SELECT DISTINCT ?eredienstSubmission ?eredienstSubmissionSentDate ?eredienst ?eredienstDocument
WHERE {
  VALUES ?gemeente { <http://data.lblod.info/id/bestuurseenheden/169b6bfa2d8ee340f266af26d1a6055182214082dca720b8817d3893692f3068> }
  VALUES ?besluitType { <https://data.vlaanderen.be/id/concept/BesluitType/e44c535d-4339-4d15-bdbf-d4be6046de2c> }

  ?betrokkenBestuur org:organization ?eredienst .
  ?gemeente ere:betrokkenBestuur ?betrokkenBestuur .

  ?eredienstSubmission
    rdf:type meb:Submission ;
    nmo:sentDate ?eredienstSubmissionSentDate ;
    pav:createdBy ?eredienst ;
    dcterms:subject ?eredienstDocument ;
    prov:generated ?eredienstFormData .

  ?eredienstFormData dcterms:type ?besluitType .

  # Enkel de meest recente inzending per ?eredienstDocument behouden:
  FILTER NOT EXISTS {
    ?newerSubmission
      rdf:type meb:Submission ;
      dcterms:subject ?eredienstDocument ;
      nmo:sentDate ?newerSentDate .
    FILTER (?newerSentDate > ?eredienstSubmissionSentDate)
  }
}
